version: 2
jobs:
  build:
    working_directory: ~/ocaml
    docker:
      - image: ocaml/opam:ubuntu
    steps:
      - checkout
      - run: opam init; eval `opam config env`; opam install cryptokit sqlite3 menhir cppo
