version: 2
jobs:
  build:
    working_directory: ~/ocaml
    docker:
      - image: ocaml/opam:ubuntu
        environment:
          OPAMYES: yes
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-opam-base
      - run:
          name: apt-get
          command: sudo apt-get install --yes zlib1g-dev libgmp-dev libgmp-ocaml-dev sqlite3 pkg-config libsqlite3-dev m4
      - run:
          name: install_libs
          command: opam install sqlite3.4.1.2 menhir cppo cryptokit
      - save_cache:
          key: dependency-cache-opam-base
          paths:
            - .opam_modules
      - run:
          name: build
          command: 'make opt'
      - run:
          name: test
          command: 'echo "(\x. x x)" | ./fly'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      
